version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"  
    networks:
      - mynetwork

  app:
    build:
      context: ./app
    expose:
      - "2210"  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
