export const topics = [
  "Articulation Point",
  "Array",
  "Binary Search",
  "Binary Search Tree",
  "Binary Tree",
  "Bit Manipulation",
  "Bitmask",
  "Breadth-First Search",
  "Bridges",
  "Bucket Sort",
  "Combinatorics",
  "Design",
  "Doubly-Linked List",
  "Disjoint Set",
  "DFS",
  "Divide and Conquer",
  "Dynamic Programming",
  "Graph",
  "Greedy",
  "Heap (Priority Queue)",
  "Hash Table",
  "Linked List",
  "Matrix",
  "Minimum Spanning Tree",
  "Monotonic Stack",
  "Merge Sort",
  "Math",
  "Number Theory",
  "Ordered Set",
  "Prefix Sum",
  "Queue",
  "Recursion",
  "Segment Tree",
  "Shortest Path",
  "Sliding Window",
  "Stack",
  "String",
  "Topological Sort",
  "Trie",
  "Two Pointers",
  "Union Find"
];