const ResourcesTitle = {
    STL : "C++ STL Handwritten Notes",
    SortingAlgorithms: 'Sorting Algorithms',
    SinglyLinkedList: 'Singly Linked List',
    GreedyApproach: 'Greedy Approach',
    HashMap: 'Hashmap/Map',
    OOPsNotes: 'OOPs Notes',
    BitManipulation: 'Bit Manipulation',
    DPPart1: 'Dynamic Programming (DP) Part-1',
    DPPart2: 'Dynamic Programming (DP) Part-2',
    OperatingSystemPart1: 'Operating System Part-1',
    OperatingSystemPart2: 'Operating System Part-2',
    ComputerNetworksNotes: 'Computer Networks Short Notes',
    CompilerDesignNotes: 'Compiler Design Notes',
    AlgorithmShortNotes: 'Algorithm Short Notes',
    OperatingSystemShortNotes: 'Operating System Short Notes',
    GraphPart1: 'Graph Part-1',
    GraphPart2: 'Graph Part-2',
    LambdaExpressionsJava: 'Lambda Expressions (Java)',
    JavaCollections: 'Java Collections',
  };
  

export const resourcesData = [
    { id: 1, title: ResourcesTitle.STL, image: "", link: "https://www.linkedin.com/posts/kapilyadav22_c-stl-notes-activity-6873598326260994048-B4Pb/" },
    { id: 2, title: ResourcesTitle.SortingAlgorithms, link: 'https://lnkd.in/gJWWHX5m' },
    { id: 3, title: ResourcesTitle.SinglyLinkedList, link: 'https://lnkd.in/gNury6T9' },
    { id: 4, title: ResourcesTitle.GreedyApproach, link: 'https://lnkd.in/gsAvp5k7' },
    { id: 5, title: ResourcesTitle.HashMap, link: 'https://lnkd.in/g9EzR2V8' },
    { id: 6, title: ResourcesTitle.OOPsNotes, link: 'https://lnkd.in/gR2HJ8TB' },
    { id: 7, title: ResourcesTitle.BitManipulation, link: 'https://lnkd.in/gcpZeetG' },
    { id: 8, title: ResourcesTitle.DPPart1, link: 'https://lnkd.in/gq_Nw8S8' },
    { id: 9, title: ResourcesTitle.DPPart2, link: 'https://lnkd.in/gXT4aRtn' },
    { id: 10, title: ResourcesTitle.OperatingSystemPart1, link: 'https://lnkd.in/gDx2sTtY' },
    { id: 11, title: ResourcesTitle.OperatingSystemPart2, link: 'https://lnkd.in/gtVXFWEg' },
    { id: 12, title: ResourcesTitle.ComputerNetworksNotes, link: 'https://lnkd.in/gdrA476E' },
    { id: 13, title: ResourcesTitle.CompilerDesignNotes, link: 'https://lnkd.in/gsy9CxQb' },
    { id: 14, title: ResourcesTitle.AlgorithmShortNotes, link: 'https://lnkd.in/gQNumHam' },
    { id: 15, title: ResourcesTitle.OperatingSystemShortNotes, link: 'https://lnkd.in/gycDD_tS' },
    { id: 16, title: ResourcesTitle.GraphPart1, link: 'https://lnkd.in/gFdD8hwH' },
    { id: 17, title: ResourcesTitle.GraphPart2, link: 'https://lnkd.in/gB5MYEzQ' },
    { id: 18, title: ResourcesTitle.LambdaExpressionsJava, link: 'https://lnkd.in/gqx5JY3F' },
    { id: 19, title: ResourcesTitle.JavaCollections, link: 'https://lnkd.in/gbyeptgB' },
  ];

